### ISSUE TITLE
Questions about the dependencies

### ISSUE THREAD

**Issue by DHuiTnut** [winycg/CIRKD#16]
Hi, thank for your excellent work! 
I encountered some environment building problems when reproducing the code. Could you please provide a detailed list of dependencies and corresponding versions?

**Comment by DHuiTnut** [comment]
And the log was the following: 

(CIRKD) root@ceb06b3e585e:~/CIRKD-main# python test.py
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    from models.model_zoo import get_segmentation_model
  File "/root/CIRKD-main/models/model_zoo.py", line 7, in <module>
    from .segformer import *
  File "/root/CIRKD-main/models/segformer.py", line 13, in <module>
    from mmcv.runner import load_checkpoint
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/mmcv/__init__.py", line 6, in <module>
    from .fileio import *
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 41, in <module>
    from .env import collect_env
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/mmcv/utils/env.py", line 13, in <module>
    from .parrots_wrapper import get_build_config
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 101, in <module>
    BuildExtension, CppExtension, CUDAExtension = _get_extension()
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 71, in _get_extension
    from torch.utils.cpp_extension import (BuildExtension, CppExtension,
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 8, in <module>
    import setuptools
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "/root/anaconda3/envs/CIRKD/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /root/anaconda3/envs/CIRKD/lib/python3.8/distutils/core.py

**Comment by winycg** [comment]
It seems that you should install mmcv package:
pip install mmcv

**Comment by DHuiTnut** [comment]
> It seems that you should install mmcv package: pip install mmcv

It does not work. T_T

**Comment by winycg** [comment]
Hi, if you do not use Segformer, the mmcv is not needed. 

Since I use segformer, I follow [https://github.com/NVlabs/SegFormer](https://github.com/NVlabs/SegFormer) to install mmcv
