### ISSUE TITLE
get error when run code with one gpu

### ISSUE THREAD

**Issue by polor1010** [winycg/CIRKD#18]
Hi, 

thank for your excellent work!~

Because of only one gpu on my machine, so I edited script file like this

CUDA_VISIBLE_DEVICES=0 \
    python -m torch.distributed.launch --nproc_per_node=1 \
    train_cirkd.py \

then I got the error message as follow

160000 images are loaded!
500 images are loaded!
Load pre-trained model successfully!------------
2023-03-25 15:29:44,496 semantic_segmentation INFO: Start training, Total Iterations 40000
Traceback (most recent call last):
  File "/home/chenxinyu/work/CIRKD/train_cirkd.py", line 476, in <module>
    trainer.train()
  File "/home/chenxinyu/work/CIRKD/train_cirkd.py", line 323, in train
    self.criterion_memory_contrast(s_outputs[-1], t_outputs[-1].detach(), targets, predict)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenxinyu/work/CIRKD/losses/cirkd_memory.py", line 123, in forward
    s_feats = self.project_head(s_feats)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 735, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1067, in get_world_size
    return _get_group_size(group)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 453, in _get_group_size
    default_pg = _get_default_group()
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 584, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2123816) of binary: /home/chenxinyu/anaconda3/envs/pytorch/bin/python
Traceback (most recent call last):
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/chenxinyu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

How do I fix it? thanks!

**Comment by winycg** [comment]
Hi, I did not test the repo over one GPU.  Some codes may appear error in dimension or distributed aggregation function. I strongly suggest you to conduct segmentation experiments on multi-GPU setup, as the widely applied practice.
