### ISSUE TITLE
The results on Cityscapes, train_cirkd.py cannot be reproduced

### ISSUE THREAD

**Issue by GiLonn** [winycg/CIRKD#31]
Hi, thanks your excellent work.

I actually follow your guidance:

[Requirement]
Ubuntu 18.04 LTS

Python 3.8 ([Anaconda](https://www.anaconda.com/) is recommended)

CUDA 11.1

PyTorch 1.8.0

NCCL for CUDA 11.1

Install python packages:

pip install timm==0.3.2
pip install mmcv-full==1.2.7
pip install opencv-python==4.5.1.48

After successfully install all packages,
and I try to reproduce your result in train_cirkd.py.

When training train_cirkd.py, the scripts such as follows:
CUDA_VISIBLE_DEVICES=0,1 \
    torchrun --nproc_per_node=2 train_cirkd.py \
    --teacher-model deeplabv3 \
    --student-model deeplabv3 \
    --teacher-backbone resnet101 \
    --student-backbone resnet18 \
    --data dataset/cityscapes/ \
    --batch-size 2 \
    --max-iterations 320000 \
    --save-dir work_dirs/deeplabv3_res18_OnlyKD_bs2 \
    --log-dir work_dirs/deeplabv3_res18_OnlyKD_bs2 \
    --teacher-pretrained pretrain/deeplabv3_resnet101_citys_best_model.pth \
    --student-pretrained-base pretrain/resnet18-imagenet.pth

Then, the terminal shows error messages as follows even after trying a lot of different ways.
Could you help figure out where the issue is?

```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2024-12-13 00:16:48,968 semantic_segmentation INFO: Using 2 GPUs
2024-12-13 00:16:48,968 semantic_segmentation INFO: Using 2 GPUs
2024-12-13 00:16:48,968 semantic_segmentation INFO: Namespace(aux=True, batch_size=2, contrast_kd_temperature=1.0, contrast_temperature=0.1, crop_size=[512, 1024], data='dataset/cityscapes/', dataset='citys', device='cpu', distributed=False, ignore_label=-1, kd_temperature=1.0, lambda_kd=1.0, lambda_memory_pixel=0.1, lambda_memory_region=0.1, lambda_minibatch_pixel=1.0, local_rank=0, log_dir='work_dirs/deeplabv3_res18_OnlyKD_bs2', log_iter=10, lr=0.02, max_iterations=320000, momentum=0.9, no_cuda=False, num_gpus=2, pixel_contrast_size=4096, pixel_memory_size=20000, region_contrast_size=1024, region_memory_size=2000, resume=None, save_dir='work_dirs/deeplabv3_res18_OnlyKD_bs2', save_epoch=10, save_per_iters=800, skip_val=False, start_epoch=0, student_backbone='resnet18', student_model='deeplabv3', student_pretrained='None', student_pretrained_base='pretrain/resnet18-imagenet.pth', teacher_backbone='resnet101', teacher_model='deeplabv3', teacher_pretrained='pretrain/deeplabv3_resnet101_citys_best_model.pth', teacher_pretrained_base='None', val_epoch=1, val_per_iters=800, weight_decay=0.0001, workers=8)
2024-12-13 00:16:48,968 semantic_segmentation INFO: Namespace(aux=True, batch_size=2, contrast_kd_temperature=1.0, contrast_temperature=0.1, crop_size=[512, 1024], data='dataset/cityscapes/', dataset='citys', device='cpu', distributed=False, ignore_label=-1, kd_temperature=1.0, lambda_kd=1.0, lambda_memory_pixel=0.1, lambda_memory_region=0.1, lambda_minibatch_pixel=1.0, local_rank=0, log_dir='work_dirs/deeplabv3_res18_OnlyKD_bs2', log_iter=10, lr=0.02, max_iterations=320000, momentum=0.9, no_cuda=False, num_gpus=2, pixel_contrast_size=4096, pixel_memory_size=20000, region_contrast_size=1024, region_memory_size=2000, resume=None, save_dir='work_dirs/deeplabv3_res18_OnlyKD_bs2', save_epoch=10, save_per_iters=800, skip_val=False, start_epoch=0, student_backbone='resnet18', student_model='deeplabv3', student_pretrained='None', student_pretrained_base='pretrain/resnet18-imagenet.pth', teacher_backbone='resnet101', teacher_model='deeplabv3', teacher_pretrained='pretrain/deeplabv3_resnet101_citys_best_model.pth', teacher_pretrained_base='None', val_epoch=1, val_per_iters=800, weight_decay=0.0001, workers=8)
640000 images are loaded!
500 images are loaded!
640000 images are loaded!
500 images are loaded!
Traceback (most recent call last):
  File "train_cirkd.py", line 501, in <module>
    trainer = Trainer(args)
  File "train_cirkd.py", line 197, in __init__
    self.t_model = get_segmentation_model(model=args.teacher_model, 
  File "/home/junli/Jun/method1/CIRKD-main/models/model_zoo.py", line 21, in get_segmentation_model
    return models[model](**kwargs)
  File "/home/junli/Jun/method1/CIRKD-main/models/deeplabv3.py", line 177, in get_deeplabv3
    model.load_state_dict(torch.load(pretrained, map_location=device))
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 973, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 152, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 136, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Traceback (most recent call last):
  File "train_cirkd.py", line 501, in <module>
    trainer = Trainer(args)
  File "train_cirkd.py", line 197, in __init__
    self.t_model = get_segmentation_model(model=args.teacher_model, 
  File "/home/junli/Jun/method1/CIRKD-main/models/model_zoo.py", line 21, in get_segmentation_model
    return models[model](**kwargs)
  File "/home/junli/Jun/method1/CIRKD-main/models/deeplabv3.py", line 177, in get_deeplabv3
    model.load_state_dict(torch.load(pretrained, map_location=device))
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 973, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 152, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/serialization.py", line 136, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15037) of binary: /home/junli/anaconda3/envs/cirkd/bin/python
Traceback (most recent call last):
  File "/home/junli/anaconda3/envs/cirkd/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.1', 'console_scripts', 'torchrun')())
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/junli/anaconda3/envs/cirkd/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_cirkd.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-12-13_00:16:53
  host      : DESKTOP-V9UB760.
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 15038)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-13_00:16:53
  host      : DESKTOP-V9UB760.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 15037)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Looking forward to your reply. Thanks!

Best Regards!

**Comment by winycg** [comment]
"torch.cuda.is_available() is False" means that your CUDA may not be ready, please check the CUDA environment.
